Arena.define('tests/animationResetV031Tests',['tests/testRunner','data/animationSourcePlan','render/animationStateMachine'],function(Arena){'use strict';var T=Arena.Tests,SP=Arena.Data.AnimationSourcePlan,S=Arena.Render.AnimationStateMachine;
T.suite('v0.32 · source/package honesty',function(){
 T.test('rig/base sigue único y sin armadura',function(){T.assertEqual(SP.baseRig,'QUATERNIUS_UAL_NATIVE_65');T.assertEqual(SP.bodyPolicy,'ONE_NATIVE_BODY_NO_ARMOR_NO_ACCESSORIES');});
 T.test('último mapping del usuario gobierna normales y power melee',function(){T.assertEqual(SP.slots.meleeNormalA.clip,'Sword_Regular_A');T.assertEqual(SP.slots.meleeNormalB.clip,'Sword_Regular_B');T.assertEqual(SP.slots.meleeWeaponPower.clip,'Sword_Regular_C');});
 T.test('recovery nativo de A/B queda explícito',function(){T.assertEqual(SP.recoveryPairs.Sword_Regular_A,'Sword_Regular_A_Rec');T.assertEqual(SP.recoveryPairs.Sword_Regular_B,'Sword_Regular_B_Rec');});
 T.test('mapping antiguo Sword_Attack queda completamente supersedido',function(){T.assert(S.clipsUsados().indexOf('Sword_Attack')<0);T.assert(!SP.slots.swordAttackLegacy);});
 T.test('Shield_Dash_RM usa fuente RM pero root sigue presentación',function(){T.assertEqual(SP.slots.shieldBash.clip,'Shield_Dash_RM');T.assertEqual(SP.rmSources.Shield_Dash_RM.sourceClip,'Shield_Dash');T.assertEqual(SP.rmSources.Shield_Dash_RM.rootPolicy,'VISUAL_ROOT_XZ_LOCKED');});
 T.test('hit mapping y knockdown mapping son literales',function(){T.assertEqual(SP.slots.hitChest.clip,'Hit_Chest');T.assertEqual(SP.slots.hitHead.clip,'Hit_Head');T.assertEqual(SP.slots.knockdownStart.clip,'Slide_Start');T.assertEqual(SP.slots.knockdownLoop.clip,'Slide_Loop');T.assertEqual(SP.slots.knockdownExit.clip,'Slide_Exit');});
 T.test('jump UAL1 reemplaza NinjaJump para esta iteración',function(){T.assertEqual(SP.jump.active.join(','),'Jump_Start,Jump_Loop,Jump_Land');var u=S.clipsUsados();T.assert(u.indexOf('NinjaJump_Start')<0);T.assert(u.indexOf('NinjaJump_Idle_Loop')<0);T.assert(u.indexOf('NinjaJump_Land')<0);});
 T.test('caster CMU queda retirado y familia Spell activa',function(){var u=S.clipsUsados();['Arena_CMU_Caster_Charge','Arena_CMU_Caster_Normal','Arena_CMU_Caster_Power'].forEach(function(n){T.assert(u.indexOf(n)<0,n);});['Spell_Simple_Enter','Spell_Simple_Exit','Spell_Simple_Idle_Loop','Spell_Simple_Shoot'].forEach(function(n){T.assert(u.indexOf(n)>=0,n);});});
 T.test('arquero conserva nombres Bow_* exactos del video y fallbacks video-derived',function(){var u=S.clipsUsados();T.assert(u.indexOf('Arena_Bow_StandardProxy')<0);['Bow_Aim_Neutral','Bow_Notch','Bow_Shoot','Bow_RapidShoot','Arena_Archer_VideoReady','Arena_Archer_VideoNotch','Arena_Archer_VideoShoot','Arena_Archer_VideoBuff'].forEach(function(n){T.assert(u.indexOf(n)>=0,n);});});
 T.test('CMU runtime queda limitado a locomoción direccional y kick',function(){T.assertEqual(SP.mocapPackAudit.runtimePolicy,'SELECT_ONLY_RETARGETED_CLIPS_NO_RAW_FBX_IN_DEPLOY');T.assert(SP.mocapPackAudit.selectedSources.indexOf('135_04.fbx')>=0);T.assert(SP.mocapPackAudit.selectedSources.indexOf('120_03.fbx')<0);});
 T.test('sockets nativos permanecen estables',function(){T.assertEqual(SP.weaponSockets.sword.bone,'RightHand');T.assertEqual(SP.weaponSockets.greatsword.secondaryGrip,'LeftHand');T.assertEqual(SP.weaponSockets.bow.bone,'LeftHand');T.assertEqual(SP.weaponSockets.staff.bone,'RightHand');T.assertEqual(SP.weaponSockets.shield.bone,'LeftLowerArm');});
});return true;});
