Arena.define('tests/animationLibraryV016Tests', ['tests/testRunner','data/animationLibraryMap','render/skinnedAnimationContract'], function (Arena) {
  'use strict';
  var T=Arena.Tests, M=Arena.Data.AnimationLibraryMap, C=Arena.Render.SkinnedAnimationContract;
  function h(){return {loco:{moveSpeed:0,cycle:0,moveForward:0,moveRight:0,airborne:false,jumpPhase:0,landingAmount:0,hipHeight:0,leanF:0,leanR:0,torsoYaw:0,torsoRoll:0,headYaw:0,breathe:0,idleAmount:1,hitAmount:0,turnRate:0},action:{family:null,t:0,variant:0},cast:0,casting:false,cc:null,ccBlend:0,ccTime:0,cfg:{phases:{light:{active:.28,impact:.55,recovery:.78,end:1}}}};}
  T.suite('v0.16 · UAL2 retarget + controles de locomoción', function(){
    T.test('biblioteca externa queda declarada CC0 y local', function(){T.assertEqual(M.license,'CC0-1.0');T.assert(/ual2-standard\.glb$/.test(M.asset),'asset no local');});
    T.test('forward usa Walk_Carry_Loop como base natural', function(){var x=h();x.loco.moveSpeed=.9;x.loco.moveForward=1;x.loco.cycle=.33;var s=M.select(x,'caster');T.assert(s&&s.clip==='Walk_Carry_Loop'&&s.locomotion,'forward no usa gait externo');T.assertEqual(s.mask,'lowerSpine');});
    T.test('strafe NO recicla caminata frontal girada', function(){var x=h();x.loco.moveSpeed=.9;x.loco.moveRight=1;x.loco.cycle=.33;T.assertEqual(M.select(x,'archer'),null,'strafe no puede fingirse con forward walk');});
    T.test('idle usa sólo base corporal UAL2 y preserva brazos de arma', function(){var x=h();x.loco.breathe=Math.PI;var s=M.select(x,'caster');T.assert(s&&s.clip==='Idle_FoldArms_Loop'&&s.idle&&s.locomotion,'idle natural no seleccionado');T.assertEqual(s.mask,'lowerSpine');T.assert(s.blend>0&&s.blend<=.62,'blend idle fuera de rango');});
    T.test('reacción al golpe usa recoil UAL2 sin secuestrar locomoción', function(){var x=h();x.loco.moveSpeed=.8;x.loco.moveForward=1;x.loco.hitAmount=.7;var s=M.select(x,'archer');T.assert(s&&s.clip==='Hit_Knockback'&&s.hitReaction,'hit externo no seleccionado');T.assertEqual(s.mask,'upperBody');T.assert(!s.locomotion,'hit no debe congelar lower body');});
    T.test('backpedal invierte fase de gait sin invertir yaw', function(){var x=h();x.loco.moveSpeed=.8;x.loco.moveForward=-1;x.loco.cycle=.20;var s=M.select(x,'caster');T.assert(s&&s.reverse,'backward no se marca reverse');T.assertBetween(s.phase,.79,.81,'fase backward incorrecta');});
    T.test('melee normal alterna clips reales A/B/C', function(){var x=h();x.action={family:'light',t:.5,variant:0};T.assertEqual(M.select(x,'melee').clip,'Sword_Regular_A');x.action.variant=1;T.assertEqual(M.select(x,'melee').clip,'Sword_Regular_B');x.action.variant=2;T.assertEqual(M.select(x,'melee').clip,'Sword_Regular_C');});
    T.test('heavy/block/charge usan familias externas distintas', function(){var x=h();x.action={family:'heavy',t:.4,variant:0};T.assertEqual(M.select(x,'melee').clip,'Sword_Heavy_Combo');x.action.family='shield';T.assertEqual(M.select(x,'melee').clip,'Shield_OneShot');x.action.family='charge';T.assertEqual(M.select(x,'melee').clip,'Sword_Dash');});
    T.test('salto separa takeoff/air/land', function(){var x=h();x.loco.airborne=true;x.loco.jumpPhase=.1;T.assertEqual(M.select(x,'caster').clip,'NinjaJump_Start');x.loco.jumpPhase=.5;T.assertEqual(M.select(x,'caster').clip,'NinjaJump_Idle_Loop');x.loco.jumpPhase=.9;T.assertEqual(M.select(x,'caster').clip,'NinjaJump_Land');});
    T.test('contrato puede ceder locomoción sin perder arma/guardia', function(){var x=h(),s=C.createState();x.loco.moveSpeed=1;x.loco.moveForward=1;x.loco.cycle=.25;C.update(s,x,'caster','arcanista',1/60,{skipLocomotion:true});T.assert(Math.abs(s.bones.LeftUpperLeg.x)<.001&&Math.abs(s.bones.RightUpperLeg.x)<.001,'locomoción procedural sigue contaminando gait externo');T.assertEqual(s.weapon.kind,'staff');T.assert(Math.abs(s.bones.RightUpperArm.x)>.05,'guardia caster desapareció');});
    T.test('full-body melee externo puede apagar guardia y acción procedural', function(){var x=h(),s=C.createState();x.action={family:'light',t:.55,variant:0};C.update(s,x,'melee','devastador',1/60,{skipLocomotion:true,skipGuard:true,skipMeleeAction:true});T.assert(Math.abs(s.bones.RightUpperArm.x)<.001,'doble animación melee');T.assertEqual(s.weapon.kind,'sword');});
  });
});
