Arena.define('tests/animationContractV031Tests',
 ['tests/testRunner','render/animationStateMachine','data/animConfig','data/animationProfiles','data/animationSourcePlan'],
 function(Arena){'use strict';
 var T=Arena.Tests,S=Arena.Render.AnimationStateMachine,SP=Arena.Data.AnimationSourcePlan,AP=Arena.Data.AnimationProfiles;
 function h(cid,arch){return {loco:{moveSpeed:0,metersPerSecond:0,moveForward:0,moveRight:0,airborne:false,jumpPhase:0,landingAmount:0,hitAmount:0,turnRate:0},action:{family:null,t:0,variant:0,visualAction:null,isPower:false},cast:0,casting:false,hurt:0,hurtReaction:'chest',cc:null,ccBlend:0,deadTime:0,cfg:Arena.Data.animConfigFor(cid,arch),intent:{classId:cid,archetype:arch,hasTarget:false,combatMode:false,visualAction:null,speedBoosted:false,crowdControl:null,castProgress:0}};}
 function move(cid,arch,f,r,mps){var x=h(cid,arch);x.loco.moveSpeed=.9;x.loco.moveForward=f;x.loco.moveRight=r;x.loco.metersPerSecond=mps===undefined?2:mps;return x;}
 T.suite('v0.32 · literal UAL + explicit combat mode mapping',function(){
  T.test('modo normal = Idle_Loop',function(){var x=h('devastador','melee');T.assertEqual(S.select(x,'melee').clip,'Idle_Loop');});
  T.test('Walk_Loop camina y Jog_Fwd_Loop corre',function(){var w=move('guardian','melee',1,0,.8),j=move('guardian','melee',1,0,2.2);T.assertEqual(S.select(w,'melee').clip,'Walk_Loop');T.assertEqual(S.select(j,'melee').clip,'Jog_Fwd_Loop');});
  T.test('Sprint_Loop sólo gobierna avance rápido con buff de velocidad',function(){var x=move('guardian','melee',1,0,3);T.assertEqual(S.select(x,'melee').clip,'Jog_Fwd_Loop');x.intent.speedBoosted=true;T.assertEqual(S.select(x,'melee').clip,'Sprint_Loop');});
  T.test('salto usa Jump_Start -> Jump_Loop -> Jump_Land',function(){var x=h('devastador','melee');x.loco.airborne=true;x.loco.jumpPhase=.10;T.assertEqual(S.select(x,'melee').clip,'Jump_Start');x.loco.jumpPhase=.5;T.assertEqual(S.select(x,'melee').clip,'Jump_Loop');x.loco.jumpPhase=.9;T.assertEqual(S.select(x,'melee').clip,'Jump_Land');});
  T.test('Devastador en combate usa Sword_Idle y Guardián Idle_Shield_Loop',function(){var d=h('devastador','melee');d.intent.hasTarget=true;d.intent.combatMode=true;T.assertEqual(S.select(d,'melee').clip,'Sword_Idle');var g=h('guardian','melee');g.intent.hasTarget=true;g.intent.combatMode=true;T.assertEqual(S.select(g,'melee').clip,'Idle_Shield_Loop');});
  T.test('normal melee alterna Sword_Regular_A y B para ambos guerreros',function(){['guardian','devastador'].forEach(function(cid){var x=h(cid,'melee');x.action={family:'light',t:.25,variant:0,isPower:false};T.assertEqual(S.select(x,'melee').clip,'Sword_Regular_A',cid+' A');x.action.variant=1;T.assertEqual(S.select(x,'melee').clip,'Sword_Regular_B',cid+' B');});});
  T.test('Sword_Regular_A/B enlazan sus clips REC durante recovery',function(){var x=h('guardian','melee');x.action={family:'light',t:.92,variant:0,isPower:false};var a=S.select(x,'melee');T.assertEqual(a.clip,'Sword_Regular_A_Rec');T.assertEqual(a.normalStage,'RECOVERY');x.action.variant=1;var b=S.select(x,'melee');T.assertEqual(b.clip,'Sword_Regular_B_Rec');T.assertEqual(b.normalStage,'RECOVERY');});
  T.test('contacto del normal permanece alineado al RELEASE de simulación',function(){var x=h('guardian','melee');x.action={family:'light',t:x.cfg.phases.light.impact,variant:0,isPower:false};T.assertNear(S.select(x,'melee').syncProgress,AP.ACTION_CLIPS.Sword_Regular_A.contact,1e-9);});
  T.test('poderes de daño de arma usan Sword_Regular_C',function(){['guardian','devastador'].forEach(function(cid){var x=h(cid,'melee');x.action={family:'heavy',t:.5,variant:0,isPower:true};T.assertEqual(S.select(x,'melee').clip,'Sword_Regular_C',cid);x.action.family='thrust';T.assertEqual(S.select(x,'melee').clip,'Sword_Regular_C',cid+' thrust');});});
  T.test('poder con escudo usa Shield_Dash_RM',function(){var x=h('guardian','melee');x.action={family:'shield',t:.4,variant:0,isPower:true};var s=S.select(x,'melee');T.assertEqual(s.clip,'Shield_Dash_RM');T.assertEqual(SP.rmSources.Shield_Dash_RM.rootPolicy,'VISUAL_ROOT_XZ_LOCKED');});
  T.test('buff de escudo usa Shield_OneShot',function(){var x=h('guardian','melee');x.action={family:'cry',t:.4,variant:0,isPower:true,visualAction:'guardBuff'};T.assertEqual(S.select(x,'melee').clip,'Shield_OneShot');});
  T.test('Puntapié conserva Front Kick y no Melee_Hook',function(){var x=h('devastador','melee');x.action={family:'kick',t:.5,variant:0,isPower:true};T.assertEqual(S.select(x,'melee').clip,'Arena_CMU_Kick');T.assert(S.clipsUsados().indexOf('Melee_Hook')<0);});
  T.test('daño normal = Hit_Chest; poder de daño = Hit_Head',function(){var x=h('guardian','melee');x.hurt=.7;x.hurtReaction='chest';T.assertEqual(S.select(x,'melee').clip,'Hit_Chest');x.hurtReaction='head';T.assertEqual(S.select(x,'melee').clip,'Hit_Head');});
  T.test('noqueo usa Slide_Start -> Slide_Loop -> Slide_Exit',function(){var x=h('guardian','melee');x.intent.crowdControl='KNOCKDOWN';x.ccBlend=.2;T.assertEqual(S.select(x,'melee').clip,'Slide_Start');x.ccBlend=.9;T.assertEqual(S.select(x,'melee').clip,'Slide_Loop');x.intent.crowdControl=null;x.cc={rootPitch:1};x.ccBlend=.5;T.assertEqual(S.select(x,'melee').clip,'Slide_Exit');});
  T.test('caster usa exclusivamente familia Spell_* en combate/carga/release',function(){var x=h('arcanista','caster');x.intent.hasTarget=true;x.intent.combatMode=true;T.assertEqual(S.select(x,'caster').clip,'Spell_Simple_Idle_Loop');x.casting=true;T.assertEqual(S.select(x,'caster').clip,'Spell_Simple_Idle_Loop');x.casting=false;x.action={family:'pulse',t:.5,variant:0,isPower:false};T.assertEqual(S.select(x,'caster').clip,'Spell_Simple_Shoot');x.action={family:'heavy',t:.5,variant:0,isPower:true};T.assertEqual(S.select(x,'caster').clip,'Spell_Simple_Shoot');T.assertEqual(SP.slots.combatEnterCaster.clip,'Spell_Simple_Enter');T.assertEqual(SP.slots.combatExitCaster.clip,'Spell_Simple_Exit');});
  T.test('arquero usa contrato Bow_* del video con fallback Arena explícito',function(){var x=h('centinela','archer');x.intent.hasTarget=true;x.intent.combatMode=true;var idle=S.select(x,'archer');T.assertEqual(idle.clip,'Bow_Aim_Neutral');T.assertEqual(idle.fallbackClip,'Arena_Archer_VideoReady');x.casting=true;x.intent.visualAction='archerPower';x.intent.castProgress=.6;var charge=S.select(x,'archer');T.assertEqual(charge.clip,'Bow_Notch');T.assertEqual(charge.fallbackClip,'Arena_Archer_VideoNotch');x.casting=false;x.action={family:'ranged',t:.5,variant:0,isPower:false};var shot=S.select(x,'archer');T.assertEqual(shot.clip,'Bow_Shoot');T.assertEqual(shot.fallbackClip,'Arena_Archer_VideoShoot');});
  T.test('locomoción direccional CMU permanece conectada',function(){T.assertEqual(S.select(move('guardian','melee',-1,0,1.2),'melee').clip,'Arena_CMU_Walk_Backward');T.assertEqual(S.select(move('guardian','melee',0,-1,1.2),'melee').clip,'Arena_CMU_Strafe_Left');T.assertEqual(S.select(move('guardian','melee',0,1,1.2),'melee').clip,'Arena_CMU_Strafe_Right');});
  T.test('Q/E conservan giro izquierda/derecha correcto',function(){var x=h('guardian','melee');x.loco.turnRate=-1;T.assertEqual(S.select(x,'melee').clip,'Arena_CMU_Turn_Left');x.loco.turnRate=1;T.assertEqual(S.select(x,'melee').clip,'Arena_CMU_Turn_Right');});
 }); return true;
});
