/* v0.34 · timing/facing adversarial gates */
Arena.define('tests/archerFacingTimingV034Tests',['tests/testRunner','render/animationStateMachine','data/animationSourcePlan','data/animationProfiles'],function(Arena){'use strict';var T=Arena.Tests,SM=Arena.Render.AnimationStateMachine,SP=Arena.Data.AnimationSourcePlan,AP=Arena.Data.AnimationProfiles;
function h(cid,arch){return {intent:{classId:cid,archetype:arch,combatMode:true,hasTarget:true,speedBoosted:false,crowdControl:null},loco:{moveSpeed:0,metersPerSecond:0,moveForward:0,moveRight:0,turnRate:0,airborne:false,jumpPhase:0,landingAmount:0},action:{family:null,t:0,variant:0,isPower:false,react:{amount:0,front:0,side:0}},cfg:{phases:{light:{impact:.42,recovery:.55},heavy:{impact:.5,recovery:.68},ranged:{impact:.56,recovery:.72}}},hurt:0,ccBlend:0,casting:false};}
T.suite('v0.34 · facing + natural playback',function(){
 T.test('arquero usa facing world-forward y no un flip ciego de pelvis',function(){var s=SM.select(h('centinela','archer'),'archer');T.assertEqual(s.clip,'Bow_Aim_Neutral');T.assert(SP.archerFacingPolicy.mode==='WORLD_FORWARD_IK');T.assert(!s.flipYOrientation);});
 T.test('notch y shoot no alteran yaw autoritativo mediante AnimationClip',function(){var x=h('centinela','archer');x.casting=true;x.intent.visualAction='archerPower';x.intent.castProgress=.5;var c=SM.select(x,'archer');T.assert(!c.flipYOrientation);x.casting=false;x.action={family:'ranged',t:.56,isPower:false,variant:0,react:{amount:0,front:0,side:0}};var a=SM.select(x,'archer');T.assert(!a.flipYOrientation);});
 T.test('REC melee deja de comprimirse al sync autoritativo',function(){var x=h('guardian','melee');x.action={family:'light',t:.82,variant:0,isPower:false,react:{amount:0,front:0,side:0}};var s=SM.select(x,'melee');T.assertEqual(s.clip,'Sword_Regular_A_Rec');T.assert(s.syncAuthoritative!==true);T.assertNear(s.rate,SP.playbackPolicy.meleeRecoveryRate,1e-9);});
 T.test('reacciones de daño se ralentizan sin alterar su clip literal',function(){var x=h('guardian','melee');x.hurt=.7;x.hurtReaction='chest';var a=SM.select(x,'melee');T.assertEqual(a.clip,'Hit_Chest');T.assertNear(a.rate,SP.playbackPolicy.hitChestRate,1e-9);x.hurtReaction='head';var b=SM.select(x,'melee');T.assertEqual(b.clip,'Hit_Head');T.assertNear(b.rate,SP.playbackPolicy.hitHeadRate,1e-9);});
 T.test('Sword_Regular_C conserva contacto pero no fuerza el 96% del clip',function(){T.assertNear(AP.ACTION_CLIPS.Sword_Regular_C.contact,.48,1e-9);T.assert(AP.ACTION_CLIPS.Sword_Regular_C.end<=.75);});
});return {};});
