Arena.define('tests/archerVideoRefinementV033Tests',['tests/testRunner','render/animationStateMachine','data/animationSourcePlan','data/animConfig'],function(Arena){'use strict';
var T=Arena.Tests,S=Arena.Render.AnimationStateMachine,SP=Arena.Data.AnimationSourcePlan;
function h(){return {loco:{moveSpeed:0,metersPerSecond:0,moveForward:0,moveRight:0,airborne:false,jumpPhase:0,landingAmount:0,turnRate:0},action:{family:null,t:0,variant:0,visualAction:null,isPower:false},casting:false,cast:0,hurt:0,cc:null,ccBlend:0,deadTime:0,cfg:Arena.Data.animConfigFor('centinela','archer'),intent:{classId:'centinela',archetype:'archer',hasTarget:true,combatMode:true,visualAction:null,speedBoosted:false,crowdControl:null,castProgress:0}};}
T.suite('v0.34 · refinamiento de arquero + facing',function(){
 T.test('combat idle usa stance full-body y ya no Idle lower + upper torcido',function(){var x=h(),s=S.select(x,'archer');T.assertEqual(s.state,'COMBAT_IDLE');T.assertEqual(s.mask,'full');T.assert(!s.directLowerBase);T.assertEqual(s.clip,'Bow_Aim_Neutral');T.assertEqual(s.fallbackClip,'Arena_Archer_VideoReady');});
 T.test('Bow_Notch estacionario conserva la base completa del arquero',function(){var x=h();x.casting=true;x.intent.visualAction='archerPower';x.intent.castProgress=.7;var s=S.select(x,'archer');T.assertEqual(s.state,'CAST_CHARGE');T.assertEqual(s.mask,'upper');T.assertEqual(s.directLowerBase,'Arena_Archer_VideoReady');T.assertEqual(s.clip,'Bow_Notch');T.assertNear(s.bowDraw,.7,1e-9);});
 T.test('release de arco estacionario no vuelve a Idle lower',function(){var x=h();x.action={family:'ranged',t:.56,variant:0,visualAction:'ranged',isPower:false};var s=S.select(x,'archer');T.assertEqual(s.state,'ACTION');T.assertEqual(s.mask,'upper');T.assertEqual(s.directLowerBase,'Arena_Archer_VideoReady');T.assertEqual(s.clip,'Bow_Shoot');T.assertEqual(s.fallbackClip,'Arena_Archer_VideoShoot');});
 T.test('al moverse en combate las piernas siguen locomoción y upper conserva guardia',function(){var x=h();x.loco.moveSpeed=.5;x.loco.metersPerSecond=2;x.loco.moveForward=1;var s=S.select(x,'archer');T.assertEqual(s.state,'RUN');T.assertEqual(s.mask,'lower');T.assertEqual(s.directUpperBase,'Arena_Archer_VideoReady');});
 T.test('contrato v0.34 conserva los videos y añade facing policy',function(){T.assertEqual(SP.contractVersion,'2026-08-20-warrior-literal-speed-facing-v034');T.assert(String(SP.slots.combatIdleArcher.reference).indexOf('20.55.49')>=0);T.assert(SP.archerFacingPolicy&&SP.archerFacingPolicy.mode==='WORLD_FORWARD_IK');T.assert(SP.archerFacingPolicy.fallbackFlipY===false);});
});return true;});
