Arena.define('tests/combatModeArcherV032Tests',['tests/testRunner','render/animationStateMachine','data/animConfig','anim/animationIntent'],function(Arena){'use strict';
var T=Arena.Tests,S=Arena.Render.AnimationStateMachine,AI=Arena.Anim.AnimationIntent;
function h(cid,arch){return {loco:{moveSpeed:0,metersPerSecond:0,moveForward:0,moveRight:0,airborne:false,jumpPhase:0,landingAmount:0,turnRate:0},action:{family:null,t:0,variant:0,visualAction:null,isPower:false},casting:false,cast:0,hurt:0,cc:null,ccBlend:0,deadTime:0,cfg:Arena.Data.animConfigFor(cid,arch),intent:{classId:cid,archetype:arch,hasTarget:false,combatMode:false,visualAction:null,speedBoosted:false,crowdControl:null,castProgress:0}};}
T.suite('v0.32 · NORMAL vs COMBAT + arquero de video',function(){
 T.test('seleccionar objetivo NO cambia Idle normal',function(){[['devastador','melee'],['guardian','melee'],['centinela','archer'],['arcanista','caster']].forEach(function(q){var x=h(q[0],q[1]);x.intent.hasTarget=true;var s=S.select(x,q[1]);T.assertEqual(s.state,'IDLE',q[0]);T.assertEqual(s.clip,'Idle_Loop',q[0]);});});
 T.test('combatMode activa guardia propia por arquetipo',function(){var d=h('devastador','melee');d.intent.combatMode=true;T.assertEqual(S.select(d,'melee').clip,'Sword_Idle');var g=h('guardian','melee');g.intent.combatMode=true;T.assertEqual(S.select(g,'melee').clip,'Idle_Shield_Loop');var a=h('centinela','archer');a.intent.combatMode=true;var as=S.select(a,'archer');T.assertEqual(as.clip,'Bow_Aim_Neutral');T.assertEqual(as.fallbackClip,'Arena_Archer_VideoReady');var c=h('arcanista','caster');c.intent.combatMode=true;T.assertEqual(S.select(c,'caster').clip,'Spell_Simple_Idle_Loop');});
 T.test('locomoción sólo recibe upper-body de combate cuando combatMode está activo',function(){var a=h('centinela','archer');a.loco.moveSpeed=1;a.loco.moveForward=1;a.loco.metersPerSecond=2;var n=S.select(a,'archer');T.assert(!n.directUpperBase,'normal sin guardia de arco');a.intent.combatMode=true;var c=S.select(a,'archer');T.assertEqual(c.directUpperBase,'Arena_Archer_VideoReady');});
 T.test('AnimationIntent transporta combatMode sin confundirlo con target',function(){var e={id:1,classId:'centinela',alive:true,yaw:0,targetId:2,combatMode:false,mods:function(){return{};},hasStatus:function(){return false;},weaponState:null,actionState:null,queuedAction:null,pendingCast:null,cast:null};var w={time:0,getEntity:function(id){return id===2?{alive:true}:null;}};var i=AI.create();AI.build(i,e,w,null,null);T.assert(i.hasTarget);T.assert(!i.combatMode);e.combatMode=true;AI.build(i,e,w,null,null);T.assert(i.combatMode);});
 T.test('Bow_Notch y Bow_Shoot mantienen fallback y draw separados',function(){var a=h('centinela','archer');a.intent.combatMode=true;a.casting=true;a.intent.visualAction='archerPower';a.intent.castProgress=.75;var n=S.select(a,'archer');T.assertEqual(n.clip,'Bow_Notch');T.assertEqual(n.fallbackClip,'Arena_Archer_VideoNotch');T.assertNear(n.bowDraw,.75,1e-9);a.casting=false;a.action={family:'ranged',t:.4,variant:0,isPower:false};var sh=S.select(a,'archer');T.assertEqual(sh.clip,'Bow_Shoot');T.assertEqual(sh.fallbackClip,'Arena_Archer_VideoShoot');T.assert(sh.bowDraw>0);});
});return true;});
