/* =============================================================================
 * render/three/threeDirectAnim.js — v0.34 · sanitized direct playback + root-motion/facing correction.
 *
 * The warrior path can use the exact 65-joint Quaternius humanoid shipped in
 * Universal Animation Library instead of approximating those clips on the
 * 17-joint legacy retarget body.  This is PRESENTATION ONLY.  Simulation still owns world
 * position/yaw, RELEASE, damage, cooldowns, GCD and target legality.
 *
 * Direct playback deliberately keeps the source skeleton for full-body actions
 * (clavicles, fingers and toe/ball joints included). Lower/upper masks are
 * generated by filtering tracks. v0.30 resolves the user-requested exact clip first.
 * If the supplied Standard binary does not contain it, an explicit fallbackClip
 * may be used for playability, but requested/resolved names stay separately
 * auditable. No fallback is ever promoted to the exact authored clip.
 * ========================================================================== */
import * as THREE from 'three';

const CANON_TO_SOURCE = Object.freeze({
  Hips:'pelvis', Spine:'spine_01', Chest:'spine_03', Neck:'neck_01', Head:'Head',
  LeftUpperArm:'upperarm_l', LeftLowerArm:'lowerarm_l', LeftHand:'hand_l',
  RightUpperArm:'upperarm_r', RightLowerArm:'lowerarm_r', RightHand:'hand_r',
  LeftUpperLeg:'thigh_l', LeftLowerLeg:'calf_l', LeftFoot:'foot_l', LeftToe:'ball_l',
  RightUpperLeg:'thigh_r', RightLowerLeg:'calf_r', RightFoot:'foot_r', RightToe:'ball_r'
});


/* --------------------------------------------------------------------------
 * Clip sanitation / retargeting
 * --------------------------------------------------------------------------
 * External FBX/GLTF exporters frequently preserve namespaces such as
 * `mixamorig:` or hierarchy wrappers such as `Armature|mixamorig:Hips`.
 * PropertyBinding resolves tracks by object name, so those prefixes must be
 * removed before the clip reaches AnimationMixer.
 *
 * IMPORTANT: this is a lightweight name/axis sanitation pass, not a full
 * skeleton retargeter. It intentionally leaves animation timing and local
 * rotations untouched except when an explicit Y-orientation correction is
 * requested for a clip authored facing -Z.
 */
const DEFAULT_BONE_ALIASES = Object.freeze({
  // Generic / canonical -> native UAL 65-joint rig.
  Hips:'pelvis', Pelvis:'pelvis',
  Spine:'spine_01', Spine1:'spine_02', Spine2:'spine_03', Chest:'spine_03',
  Neck:'neck_01', Head:'Head',
  LeftShoulder:'clavicle_l', LeftArm:'upperarm_l', LeftUpperArm:'upperarm_l',
  LeftForeArm:'lowerarm_l', LeftLowerArm:'lowerarm_l', LeftHand:'hand_l',
  RightShoulder:'clavicle_r', RightArm:'upperarm_r', RightUpperArm:'upperarm_r',
  RightForeArm:'lowerarm_r', RightLowerArm:'lowerarm_r', RightHand:'hand_r',
  LeftUpLeg:'thigh_l', LeftUpperLeg:'thigh_l', LeftLeg:'calf_l', LeftLowerLeg:'calf_l',
  LeftFoot:'foot_l', LeftToeBase:'ball_l', LeftToe:'ball_l',
  RightUpLeg:'thigh_r', RightUpperLeg:'thigh_r', RightLeg:'calf_r', RightLowerLeg:'calf_r',
  RightFoot:'foot_r', RightToeBase:'ball_r', RightToe:'ball_r'
});

const DEFAULT_ROOT_MOTION_BONES = new Set(['hips','pelvis']);
const FAST_TRANSITION_RE = /(ACTION|ATTACK|MELEE|DODGE|EVADE|ROLL|HIT|BLOCK|PARRY|KNOCK|INTERRUPT|JUMP_START|LAND)/i;
const LOCOMOTION_TRANSITION_RE = /(IDLE|COMBAT_IDLE|WALK|RUN|SPRINT|BACKPEDAL|STRAFE|DIAGONAL|TURN|AIRBORNE)/i;

function collectTargetNames(root) {
  const names = new Set();
  if (root && typeof root.traverse === 'function') {
    root.traverse(o => { if (o && o.name) names.add(o.name); });
  }
  return names;
}

function splitTrackName(trackName) {
  const dot = trackName.lastIndexOf('.');
  if (dot <= 0) return { node:trackName, property:'' };
  return { node:trackName.slice(0, dot), property:trackName.slice(dot + 1) };
}

function stripHierarchyPrefix(nodeName) {
  let node = String(nodeName || '').trim();

  // THREE.PropertyBinding may serialize bone access as Armature.bones[Bone].
  const bonesMatch = node.match(/(?:^|\.bones\[)([^\]]+)\]$/);
  if (bonesMatch) node = bonesMatch[1].replace(/^['\"]|['\"]$/g, '');

  // Keep only the leaf object when an exporter embeds hierarchy paths.
  const pathParts = node.split(/[\\/|]/);
  node = pathParts[pathParts.length - 1] || node;

  // Strip one or more namespaces: `mixamorig:Hips`, `ns:rig:Hips`, etc.
  if (node.includes(':')) node = node.split(':').pop();

  // Mixamo commonly exports both `mixamorig:Hips` and `mixamorigHips`.
  node = node.replace(/^mixamorig[_-]?/i, '');

  return node.trim();
}

function resolveTargetBoneName(cleanName, targetNames, boneMap) {
  if (!cleanName) return cleanName;
  if (targetNames && targetNames.has(cleanName)) return cleanName;
  const mapped = boneMap && boneMap[cleanName];
  if (mapped && (!targetNames || !targetNames.size || targetNames.has(mapped))) return mapped;
  return cleanName;
}

function cloneTrackWithName(track, newName) {
  const out = track.clone();
  out.name = newName;
  // Be explicit: source arrays must never be mutated by later correction passes.
  out.times = new Float32Array(track.times);
  out.values = new Float32Array(track.values);
  return out;
}

/**
 * Clone and sanitize an AnimationClip before it reaches AnimationMixer.
 *
 * options:
 * - targetRoot: native character root (used to resolve bone aliases safely).
 * - boneMap: optional aliases merged over DEFAULT_BONE_ALIASES.
 * - stripRootMotion: default true; auto-removes source root translation while
 *   preserving native UAL child-pelvis motion when a separate `root` exists.
 * - rootMotionBones: optional iterable of bone names considered locomotion roots.
 * - flipYOrientation: false | true | angleInRadians. true == Math.PI.
 * - orientationBone: preferred bone for the offset (e.g. 'Hips' or 'Spine').
 */
export function sanitizeAnimationClip(clip, options = {}) {
  if (!clip) return null;

  const targetNames = options.targetNames || collectTargetNames(options.targetRoot || null);
  const boneMap = Object.assign({}, DEFAULT_BONE_ALIASES, options.boneMap || {});
  const stripRootMotion = options.stripRootMotion !== false;
  const customRoots = options.rootMotionBones ? Array.from(options.rootMotionBones) : null;
  const rootMotionBones = customRoots
    ? new Set(customRoots.map(n => String(n).toLowerCase()))
    : null;
  const targetHasSeparateRoot = targetNames.has('root');

  const tracks = [];
  for (const sourceTrack of clip.tracks || []) {
    const parsed = splitTrackName(sourceTrack.name);
    const cleanNode = stripHierarchyPrefix(parsed.node);
    const targetNode = resolveTargetBoneName(cleanNode, targetNames, boneMap);
    const property = parsed.property;

    // Root motion is simulation-authoritative in Arena. Remove the entire
    // translation track from Hips/Pelvis; rotation remains available.
    const cleanLower = cleanNode.toLowerCase();
    const targetLower = targetNode.toLowerCase();
    let isRootPosition = false;
    if (property === 'position') {
      if (rootMotionBones) {
        // Strict caller-defined policy.
        isRootPosition = rootMotionBones.has(cleanLower) || rootMotionBones.has(targetLower);
      } else {
        /* AUTO policy:
         * - Mixamo `Hips.position` / generic `Pelvis.position` is root motion.
         * - Native UAL has a separate `root` bone AND an animated lowercase
         *   `pelvis`; stripping that pelvis track destroys vertical weight,
         *   crouch and landing motion. In that rig we strip `root.position`
         *   and keep the child pelvis translation.
         */
        isRootPosition = cleanLower === 'root' || cleanLower === 'hips' || cleanNode === 'Pelvis';
        if (cleanLower === 'pelvis' && !targetHasSeparateRoot) isRootPosition = true;
      }
    }
    if (stripRootMotion && isRootPosition) continue;

    tracks.push(cloneTrackWithName(sourceTrack, targetNode + (property ? '.' + property : '')));
  }

  let out = new THREE.AnimationClip(clip.name, clip.duration, tracks, clip.blendMode);
  out.userData = Object.assign({}, clip.userData || {}, { arenaSanitized:true });

  if (options.flipYOrientation) {
    out = applyYOrientationOffset(out, {
      angle: typeof options.flipYOrientation === 'number' ? options.flipYOrientation : Math.PI,
      orientationBone: options.orientationBone,
      targetRoot: options.targetRoot,
      boneMap
    });
  }
  return out;
}

/** Apply a local-space facing correction to ONE orientation bone only. */
export function applyYOrientationOffset(clip, options = {}) {
  if (!clip) return null;
  const angle = Number.isFinite(options.angle) ? options.angle : Math.PI;
  const targetNames = collectTargetNames(options.targetRoot || null);
  const boneMap = Object.assign({}, DEFAULT_BONE_ALIASES, options.boneMap || {});

  const preferredRaw = options.orientationBone || 'Hips';
  const preferredClean = stripHierarchyPrefix(preferredRaw);
  const preferred = resolveTargetBoneName(preferredClean, targetNames, boneMap);

  // Never offset Hips AND Spine together: two 180° corrections would cancel
  // globally while twisting the hierarchy between the two joints.
  const candidates = [preferred, 'pelvis', 'Hips', 'Pelvis', 'spine_01', 'Spine'];
  let chosen = null;
  for (const candidate of candidates) {
    if (!candidate) continue;
    if ((clip.tracks || []).some(t => {
      const p = splitTrackName(t.name);
      return p.property === 'quaternion' && stripHierarchyPrefix(p.node) === candidate;
    })) { chosen = candidate; break; }
  }
  if (!chosen) return clip.clone();

  const qOffset = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), angle);
  const qFrame = new THREE.Quaternion();
  const tracks = (clip.tracks || []).map(sourceTrack => {
    const parsed = splitTrackName(sourceTrack.name);
    const out = cloneTrackWithName(sourceTrack, sourceTrack.name);
    if (parsed.property !== 'quaternion' || stripHierarchyPrefix(parsed.node) !== chosen) return out;

    for (let i = 0; i < out.values.length; i += 4) {
      qFrame.fromArray(out.values, i);
      qFrame.premultiply(qOffset).normalize();
      qFrame.toArray(out.values, i);
    }
    return out;
  });

  const out = new THREE.AnimationClip(clip.name, clip.duration, tracks, clip.blendMode);
  out.userData = Object.assign({}, clip.userData || {}, {
    arenaFacingOffsetY:angle,
    arenaFacingOffsetBone:chosen
  });
  return out;
}

function clampFade(v, fallback) {
  return Math.max(0.01, Math.min(0.60, Number.isFinite(v) ? v : fallback));
}

/**
 * Dynamic cross-fade policy. Existing `sel.fade` remains the highest-priority
 * override, so threeCharacter.js stays fully compatible.
 */
function resolveCrossFadeDuration(sel, previousState) {
  if (sel && Number.isFinite(sel.fade)) return clampFade(sel.fade, 0.12);
  const transition = String((sel && (sel.transitionType || sel.transition)) || '').toLowerCase();
  if (transition === 'fast' || transition === 'combat' || transition === 'attack' || transition === 'dodge') return 0.065;
  if (transition === 'locomotion' || transition === 'idle' || transition === 'soft') return 0.24;

  const nextState = String((sel && sel.state) || '');
  const prevState = String(previousState || '');
  if (FAST_TRANSITION_RE.test(nextState) || FAST_TRANSITION_RE.test(prevState)) return 0.065;
  if (LOCOMOTION_TRANSITION_RE.test(nextState) || LOCOMOTION_TRANSITION_RE.test(prevState)) return 0.24;
  return 0.12;
}

/* UAL contains extra joints not representable by the legacy retarget body. Keep them when
 * they belong to the requested body region, especially clavicles/fingers for
 * weapon actions and ball/toe joints for foot contact. */
const LOWER = new Set([
  'root','pelvis','spine_01','spine_02','spine_03',
  'thigh_l','calf_l','foot_l','ball_l','ball_leaf_l',
  'thigh_r','calf_r','foot_r','ball_r','ball_leaf_r'
]);
const UPPER = new Set([
  'spine_01','spine_02','spine_03','neck_01','Head',
  'clavicle_l','upperarm_l','lowerarm_l','hand_l',
  'thumb_01_l','thumb_02_l','thumb_03_l','thumb_04_leaf_l',
  'index_01_l','index_02_l','index_03_l','index_04_leaf_l',
  'middle_01_l','middle_02_l','middle_03_l','middle_04_leaf_l',
  'ring_01_l','ring_02_l','ring_03_l','ring_04_leaf_l',
  'pinky_01_l','pinky_02_l','pinky_03_l','pinky_04_leaf_l',
  'clavicle_r','upperarm_r','lowerarm_r','hand_r',
  'thumb_01_r','thumb_02_r','thumb_03_r','thumb_04_leaf_r',
  'index_01_r','index_02_r','index_03_r','index_04_leaf_r',
  'middle_01_r','middle_02_r','middle_03_r','middle_04_leaf_r',
  'ring_01_r','ring_02_r','ring_03_r','ring_04_leaf_r',
  'pinky_01_r','pinky_02_r','pinky_03_r','pinky_04_leaf_r'
]);

function nodeOfTrack(track) {
  /* PropertyBinding track names used by the UAL GLBs are `bone.property`.
     Keep this conservative: if a future exporter adds a path prefix, the raw
     full clip still works and the masked clip will loudly omit that track. */
  const i = track.name.lastIndexOf('.');
  return i > 0 ? track.name.slice(0, i) : track.name;
}

function maskClip(clip, mask) {
  if (!clip || mask === 'full' || !mask) return clip;
  const allowed = mask === 'upper' ? UPPER : LOWER;
  const tracks = clip.tracks.filter(t => allowed.has(nodeOfTrack(t)));
  if (!tracks.length) return null;
  return new THREE.AnimationClip(clip.name + '__' + mask, clip.duration, tracks, clip.blendMode);
}

/* v0.30 · ANIMATION STATE FOUNDATION.
 *
 * Las funciones históricas que deformaban Jog_Fwd_Loop para fabricar
 * backpedal/strafe/turn y el generador de clips keyframed Arena se eliminaron
 * físicamente de este runtime. Los clips ausentes no se sintetizan: permanecen
 * BLOCKED_SOURCE_CLIP hasta que exista el archivo UAL correspondiente.
 */



function buildStaticUpperPose(raw, sourceName, progress, outName) {
  /* v0.30 · Source-derived READY POSE only.
   *
   * A sampled pose may define how an archetype HOLDS itself in combat, but it
   * must never impersonate a missing attack/cast.  Sampling a real UAL clip at
   * one audited frame is safer than applying legacy Euler offsets to this
   * 65-joint rig.  The resulting clip is constant for one second and contains
   * upper-body tracks only. */
  const src = raw[sourceName];
  if (!src) return null;
  const t = Math.max(0, Math.min(1, Number(progress) || 0)) * src.duration;
  const tracks = [];
  for (const tr of src.tracks) {
    const node = nodeOfTrack(tr);
    if (!UPPER.has(node)) continue;
    const sample = Array.from(tr.createInterpolant().evaluate(t));
    const tc = tr.clone();
    tc.times = new Float32Array([0, 1]);
    tc.values = new Float32Array(sample.concat(sample));
    tracks.push(tc);
  }
  return tracks.length ? new THREE.AnimationClip(outName, 1.0, tracks) : null;
}


function buildVideoArcherClips(raw) {
  /* v0.33 · VIDEO-REFINED ARCHER FALLBACKS.
   *
   * The user's second gameplay video exposed the remaining flaw in v0.32:
   * only the upper body was sampled while Idle_Loop owned pelvis/legs. The
   * result was a visibly twisted archer — feet/pelvis square to the target,
   * chest trying to behave like a side-on bow stance. The reference UAL2
   * viewer shows a staggered, wider base under Bow_Aim_Neutral.
   *
   * Until the real Bow_* Source clips are available we therefore build a
   * conservative FULL-BODY fallback. Pistol_Aim_Neutral contributes only the
   * same-rig stance geometry (staggered feet/pelvis) and left-side scaffold;
   * Pistol_Reload contributes the right-side timing scaffold. A dedicated
   * two-bone bow constraint in threeCharacter.js then places the two hands in
   * bow-specific targets. No pistol clip is exposed as an Arena semantic action.
   */
  const aim = raw.Pistol_Aim_Neutral, reload = raw.Pistol_Reload, idle = raw.Idle_Loop;
  if (!aim || !reload || !idle) return [];
  const by = clip => new Map((clip.tracks || []).map(t => [t.name, t]));
  const aimBy=by(aim), reloadBy=by(reload), idleBy=by(idle);
  const baseTracks=(aim.tracks||[]); // v0.33: full body, not UPPER-only.
  function sample(map,name,p,dur){
    const tr=map.get(name); if(!tr)return null;
    return Array.from(tr.createInterpolant().evaluate(Math.max(0,Math.min(1,p))*dur));
  }
  function build(name,times,selector){
    const tracks=[];
    for(const base of baseTracks){
      const node=nodeOfTrack(base), valueSize=base.getValueSize(), vals=[];
      for(let i=0;i<times.length;i++){
        const choice=selector(node,base.name,i);
        const map=choice.src==='reload'?reloadBy:(choice.src==='idle'?idleBy:aimBy);
        const dur=choice.src==='reload'?reload.duration:(choice.src==='idle'?idle.duration:aim.duration);
        const v=sample(map,base.name,choice.p,dur) || sample(aimBy,base.name,.50,aim.duration);
        if(!v)continue;
        for(let j=0;j<valueSize;j++)vals.push(v[j]);
      }
      if(vals.length!==times.length*valueSize)continue;
      const tc=base.clone(); tc.times=new Float32Array(times); tc.values=new Float32Array(vals); tracks.push(tc);
    }
    return tracks.length?new THREE.AnimationClip(name,times[times.length-1],tracks):null;
  }
  function right(node){return /_r$/.test(node)||/_r\./.test(node);}
  function left(node){return /_l$/.test(node)||/_l\./.test(node);}
  function torso(node){return /^spine_|^neck_|^Head$/.test(node);}
  function lower(node){return LOWER.has(node) && !torso(node);}

  const ready=build('Arena_Archer_VideoReady',[0,1],(node,n,i)=>{
    /* Lower body stays on the audited Pistol_Aim stance. Upper body remains a
       same-rig scaffold only; hand placement is corrected afterwards by IK. */
    if(lower(node))return {src:'aim',p:.50};
    if(right(node))return {src:'reload',p:.43};
    if(left(node)||torso(node))return {src:'aim',p:.50};
    return {src:'aim',p:.50};
  });
  const notch=build('Arena_Archer_VideoNotch',[0,.30,.68,1],(node,n,i)=>{
    if(lower(node))return {src:'aim',p:.50};
    const rp=[.30,.38,.48,.56][i];
    const ap=[.48,.50,.50,.50][i];
    if(right(node))return {src:'reload',p:rp};
    if(left(node)||torso(node))return {src:'aim',p:ap};
    return {src:'aim',p:.50};
  });
  const shoot=build('Arena_Archer_VideoShoot',[0,.42,.56,.72,1],(node,n,i)=>{
    if(lower(node))return {src:'aim',p:.50};
    const rp=[.56,.58,.68,.61,.43][i];
    const ap=[.50,.50,.51,.50,.50][i];
    if(right(node))return {src:'reload',p:rp};
    if(left(node)||torso(node))return {src:'aim',p:ap};
    return {src:'aim',p:.50};
  });
  const buff=buildStaticUpperPose(raw,'Idle_Loop',.22,'Arena_Archer_VideoBuff');
  return [ready,notch,shoot,buff].filter(Boolean);
}

export function createDirectLibrary(Arena, sourceGltf, targetRoot, options = {}) {
  if (!Arena || !sourceGltf || !targetRoot) return null;
  const raw = Object.create(null), cache = Object.create(null);

  const arenaSanitize = (Arena.Render && Arena.Render.directAnimationSanitizeOptions) || {};
  const sanitizeOptions = Object.assign({}, arenaSanitize, options.sanitize || {}, { targetRoot });
  (sourceGltf.animations || []).forEach(sourceClip => {
    if (raw[sourceClip.name]) return;
    const clipOptions = Object.assign({}, sanitizeOptions);
    const perClipRules = options.clipRules || (Arena.Render && Arena.Render.directAnimationClipRules) || null;
    const rule = perClipRules && perClipRules[sourceClip.name];
    if (rule) Object.assign(clipOptions, rule);
    const sanitized = sanitizeAnimationClip(sourceClip, clipOptions);
    if (sanitized) raw[sourceClip.name] = sanitized;
  });

  /* v0.32: video-derived bow fallbacks. Exact Bow_* names remain requested
     upstream; these authored clips are only used while Source is unavailable. */
  const authoredNames = [], derivedNames = [];
  const archerVideoClips = buildVideoArcherClips(raw);
  archerVideoClips.forEach(c => { raw[c.name] = c; derivedNames.push(c.name); });

  function has(name) { return !!raw[name]; }
  function clipFor(name, mask, upperBase, upperBaseProgress, lowerBase, lowerBaseProgress, processOptions) {
    const c = raw[name]; if (!c) return null;
    const hold = Number.isFinite(upperBaseProgress) ? Math.max(0,Math.min(1,upperBaseProgress)) : null;
    const lowerHold = Number.isFinite(lowerBaseProgress) ? Math.max(0,Math.min(1,lowerBaseProgress)) : null;
    const flipAngle = processOptions && processOptions.flipYOrientation
      ? (typeof processOptions.flipYOrientation === 'number' ? processOptions.flipYOrientation : Math.PI)
      : 0;
    const orientationBone = processOptions && processOptions.orientationBone ? processOptions.orientationBone : '';
    const key = name + ':' + (mask || 'full') + ':' + (upperBase || '') + ':' + (hold===null?'live':hold.toFixed(4)) + ':' + (lowerBase || '') + ':' + (lowerHold===null?'live':lowerHold.toFixed(4)) + ':flipY=' + flipAngle.toFixed(6) + ':' + orientationBone;
    if (cache[key]) return cache[key];
    const primary = maskClip(c, mask || 'full');
    if (!primary) return null;
    const finalize = candidate => {
      if (!candidate) return candidate;
      if (!flipAngle) return candidate;
      return applyYOrientationOffset(candidate, {
        angle:flipAngle,
        orientationBone:orientationBone || undefined,
        targetRoot
      });
    };

    /* Lower action + upper ready hold (combat locomotion / kick). */
    if (upperBase && mask === 'lower' && raw[upperBase]) {
      const up = maskClip(raw[upperBase], 'upper');
      if (!up) return (cache[key] = finalize(primary));
      const ratio = primary.duration / Math.max(1e-5, up.duration);
      const upperTracks = [];
      for (const tr of up.tracks) {
        const node = nodeOfTrack(tr);
        if (LOWER.has(node)) continue; // primary owns pelvis/spine overlap
        const tc = tr.clone();
        if (hold !== null) {
          const sample = Array.from(tr.createInterpolant().evaluate(hold * up.duration));
          tc.times = new Float32Array([0, primary.duration]);
          tc.values = new Float32Array(sample.concat(sample));
        } else tc.times = new Float32Array(Array.from(tr.times, t => t * ratio));
        upperTracks.push(tc);
      }
      return (cache[key] = finalize(new THREE.AnimationClip(
        name + '__lower+' + upperBase + '__upper', primary.duration,
        primary.tracks.concat(upperTracks), primary.blendMode)));
    }

    /* v0.30 · Upper mocap action + stable idle lower body. This is used for
       archery and magic: the actor may rotate/translate in the source capture,
       but Arena must keep the character planted while simulation owns world
       motion. Overlapping spine tracks are owned by the upper action; only
       pelvis/legs are imported from the lower base. */
    if (lowerBase && mask === 'upper' && raw[lowerBase]) {
      const low = maskClip(raw[lowerBase], 'lower');
      if (!low) return (cache[key] = finalize(primary));
      const ratio = primary.duration / Math.max(1e-5, low.duration);
      const lowerTracks = [];
      for (const tr of low.tracks) {
        const node = nodeOfTrack(tr);
        if (UPPER.has(node)) continue; // action owns spine overlap
        const tc = tr.clone();
        if (lowerHold !== null) {
          const sample = Array.from(tr.createInterpolant().evaluate(lowerHold * low.duration));
          tc.times = new Float32Array([0, primary.duration]);
          tc.values = new Float32Array(sample.concat(sample));
        } else tc.times = new Float32Array(Array.from(tr.times, t => t * ratio));
        lowerTracks.push(tc);
      }
      return (cache[key] = finalize(new THREE.AnimationClip(
        name + '__upper+' + lowerBase + '__lower', primary.duration,
        primary.tracks.concat(lowerTracks), primary.blendMode)));
    }

    return (cache[key] = finalize(primary));
  }

  function resolveSelection(sel) {
    if (!sel) return null;
    if (sel.clip && has(sel.clip)) return { name:sel.clip, fallback:false, requested:sel.clip };
    if (sel.fallbackClip && has(sel.fallbackClip)) return { name:sel.fallbackClip, fallback:true, requested:sel.clip || sel.requestedClip || null };
    return null;
  }

  const lib = {
    mode:'DIRECT_UAL_65_EXACT_CONTRACT',
    raw,
    authoredNames,
    derivedNames,
    canonicalMap:CANON_TO_SOURCE,
    has,
    clipFor,
    resolveSelection,
    createPlayer: null
  };
  lib.createPlayer = root => new DirectPlayer(lib, root);
  return lib;
}

function DirectPlayer(lib, root) {
  this.lib = lib;
  this.root = root;
  this.mixer = new THREE.AnimationMixer(root);
  this.actual = null;
  this.accion = null;
  this.estado = null;
  this.tiempoEstado = 0;
  this.ultimoRate = 1;
  this.syncProgress = null;
  this.syncDuration = 0;
  this.phaseGroup = null;
  this.requestedClip = null;
  this.resolvedClip = null;
  this.usedFallback = false;
  this.rootBone = root.getObjectByName('root') || null;
  this.rootBindPos = this.rootBone ? this.rootBone.position.clone() : null;
}

DirectPlayer.prototype.play = function(sel, dt) {
  this.tiempoEstado += dt || 0;
  const resolved = this.lib.resolveSelection(sel);
  this.requestedClip = sel ? (sel.clip || sel.requestedClip || null) : null;
  this.resolvedClip = resolved ? resolved.name : null;
  this.usedFallback = !!(resolved && resolved.fallback);

  if (!sel || !resolved) {
    if (this.actual && this.accion) {
      this.accion.fadeOut(resolveCrossFadeDuration(sel || { state:null }, this.estado));
      this.actual = null; this.accion = null;
    }
    this.syncProgress = null; this.syncDuration = 0;
    this.estado = sel ? sel.state : null;
    return false;
  }

  const resolvedUpper = sel.directUpperBase && this.lib.has(sel.directUpperBase)
    ? sel.directUpperBase
    : (sel.fallbackUpperBase && this.lib.has(sel.fallbackUpperBase) ? sel.fallbackUpperBase : null);
  const resolvedLower = sel.directLowerBase && this.lib.has(sel.directLowerBase) ? sel.directLowerBase : null;
  const clip = this.lib.clipFor(
    resolved.name,
    sel.mask || 'full',
    resolvedUpper,
    sel.directUpperBaseProgress,
    resolvedLower,
    sel.directLowerBaseProgress,
    {
      flipYOrientation: sel.flipYOrientation || false,
      orientationBone: sel.orientationBone || sel.flipYBone || null
    }
  );
  if (!clip) return false;

  const holdKey=Number.isFinite(sel.directUpperBaseProgress)?Math.max(0,Math.min(1,sel.directUpperBaseProgress)).toFixed(4):'live';
  const lowerHoldKey=Number.isFinite(sel.directLowerBaseProgress)?Math.max(0,Math.min(1,sel.directLowerBaseProgress)).toFixed(4):'live';
  /* Key by the clip that is ACTUALLY playing. BowNotch and BowShoot may both
     resolve to the same Standard proxy; in that case the mixer must not reset
     at authoritative RELEASE. Exact Source clips, once supplied, naturally
     produce distinct keys and a real Notch -> Shoot transition. */
  const flipKey = sel.flipYOrientation
    ? (typeof sel.flipYOrientation === 'number' ? sel.flipYOrientation : Math.PI).toFixed(6)
    : '0';
  const orientationKey = sel.orientationBone || sel.flipYBone || '';
  const key = resolved.name + ':' + (sel.mask || 'full') + ':' + (resolvedUpper || '') + ':' + holdKey + ':' + (resolvedLower || '') + ':' + lowerHoldKey + ':flipY=' + flipKey + ':' + orientationKey;
  if (key !== this.actual) {
    const prev = this.accion;
    let phase = null;
    if (prev && sel.loop && sel.phaseGroup && sel.phaseGroup === this.phaseGroup) {
      const oldClip = prev.getClip();
      if (oldClip && oldClip.duration > 1e-5) phase = ((prev.time / oldClip.duration) % 1 + 1) % 1;
    }
    const next = this.mixer.clipAction(clip);
    next.enabled = true;
    next.setLoop(sel.loop ? THREE.LoopRepeat : THREE.LoopOnce, sel.loop ? Infinity : 1);
    next.clampWhenFinished = !sel.loop;
    next.reset();
    if (phase !== null) next.time = phase * clip.duration;
    else if (Number.isFinite(sel.rate) && sel.rate < 0) next.time = Math.max(0, clip.duration - 1e-5);
    next.play();
    if (prev && prev !== next) {
      const fadeDuration = resolveCrossFadeDuration(sel, this.estado);
      // Explicit crossFadeTo keeps transition policy centralized while leaving
      // all existing threeCharacter.js selectors (`sel.fade`) compatible.
      prev.crossFadeTo(next, fadeDuration, false);
    } else next.setEffectiveWeight(1);
    this.accion = next;
    this.actual = key;
    this.estado = sel.state;
    this.phaseGroup = sel.phaseGroup || null;
    this.tiempoEstado = 0;
  } else if (sel.state !== this.estado) {
    this.estado = sel.state; this.phaseGroup = sel.phaseGroup || this.phaseGroup; this.tiempoEstado = 0;
  }

  const rate = Number.isFinite(sel.rate) ? sel.rate : 1;
  if (this.accion && Math.abs(rate - this.ultimoRate) > 1e-3) {
    this.accion.setEffectiveTimeScale(rate);
    this.ultimoRate = rate;
  }
  if (sel.window && sel.amount !== undefined && this.accion) {
    const a = sel.window[0] * clip.duration, b = sel.window[1] * clip.duration;
    this.accion.time = a + (1 - Math.max(0, Math.min(1, sel.amount))) * (b-a);
  }

  const requestedProgress = resolved.fallback && Number.isFinite(sel.fallbackSyncProgress)
    ? sel.fallbackSyncProgress : sel.syncProgress;
  if (sel.syncAuthoritative && Number.isFinite(requestedProgress) && this.accion) {
    this.syncProgress = Math.max(0, Math.min(1, requestedProgress));
    this.syncDuration = clip.duration;
    this.accion.time = this.syncProgress * this.syncDuration;
  } else {
    this.syncProgress = null; this.syncDuration = 0;
  }
  return true;
};

DirectPlayer.prototype._lockVisualRoot = function() {
  if (!this.rootBone || !this.rootBindPos) return;
  /* World translation remains the simulation parent's job. Keep vertical
     animation (landing/death compression) but discard clip X/Z travel. */
  this.rootBone.position.x = this.rootBindPos.x;
  this.rootBone.position.z = this.rootBindPos.z;
};

DirectPlayer.prototype.update = function(dt) {
  this.mixer.update(Math.max(0, Math.min(0.10, dt || 0)));
  if (this.accion && this.syncProgress !== null && this.syncDuration > 0) {
    this.accion.time = this.syncProgress * this.syncDuration;
    this.mixer.update(0);
  }
  this._lockVisualRoot();
};

DirectPlayer.prototype.dispose = function() {
  this.mixer.stopAllAction();
  this.mixer.uncacheRoot(this.root);
  this.lib = null; this.root = null; this.accion = null; this.actual = null;
  this.syncProgress = null; this.syncDuration = 0; this.phaseGroup = null; this.requestedClip = null; this.resolvedClip = null; this.usedFallback = false; this.rootBone = null;
};
